### ISSUE TITLE
Задачи из тинкофф - замечания

### ISSUE THREAD

**Issue by MerrickGit** [backside360/algorithms#5]
### Checkpass
`@return {string} - Возвращает результат проверки пароля`

из функции необходимо возвращать строку, а выводить ее в консоль уже не внутри.

Вызов лога делать не внутри функции
console.log(checkPass("sSssssss11"));

---

### smallestDividerRecursive

Рекурсия

`const minDiv = (n, i = 2) => n % i === 0 ? i : minDiv(n, i + 1);`

---

### totalPathRecursive

Поменять на аргумент функции

`var day = 0;`

---

**Comment by backside360** [comment]
поправил)
